import {createHash} from 'node:crypto';
import {readFileSync,writeFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {resolve} from 'node:path';
const root=fileURLToPath(new URL('../',import.meta.url));
const files=['index.html','style.css','app.js','core.js','storage.js','manifest.webmanifest','icons/icon.svg','icons/icon-192.png','icons/icon-512.png','icons/apple-touch-icon.png'];
const hashes=Object.fromEntries(files.map(path=>[path,createHash('sha256').update(readFileSync(resolve(root,path))).digest('hex')]));
const version=createHash('sha256').update(JSON.stringify(hashes)).digest('hex').slice(0,16);
const source=`// GENERATED by npm run prepare:release. Do not edit directly.
const HASHES=${JSON.stringify(hashes)};
const PREFIX='mygolf-shell-'+self.registration.scope+'-';
const CACHE=PREFIX+'${version}';
const fileURL=path=>new URL(path,self.registration.scope).href;
self.addEventListener('install',e=>e.waitUntil((async()=>{
 // Validate every response before opening the new cache. Partial deploys keep the old worker.
 const responses=await Promise.all(Object.entries(HASHES).map(async([path,expected])=>{
  const response=await fetch(new Request(fileURL(path),{cache:'reload',signal:AbortSignal.timeout(20000)}));
  if(!response.ok)throw new Error('Asset unavailable: '+path);
  const bytes=await response.clone().arrayBuffer();
  const actual=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),b=>b.toString(16).padStart(2,'0')).join('');
  if(actual!==expected)throw new Error('Asset version mismatch: '+path);
  return [path,response];
 }));
 try{const cache=await caches.open(CACHE);await Promise.all(responses.map(([path,response])=>cache.put(fileURL(path),response)));}
 catch(error){await caches.delete(CACHE);throw error;}
})()));
self.addEventListener('message',e=>{if(e.data?.type==='SKIP_WAITING')e.waitUntil(self.skipWaiting());});
self.addEventListener('activate',e=>e.waitUntil((async()=>{
 await self.clients.claim();
 // Only remove this app's superseded shell caches, never IndexedDB or unrelated caches.
 await Promise.all((await caches.keys()).filter(k=>k.startsWith(PREFIX)&&k!==CACHE).map(k=>caches.delete(k)));
})()));
self.addEventListener('fetch',e=>{
 if(e.request.method!=='GET')return;
 const url=new URL(e.request.url),scope=new URL(self.registration.scope);
 if(url.origin!==scope.origin||!url.pathname.startsWith(scope.pathname))return;
 const path=url.pathname.slice(scope.pathname.length);
 const shellPath=(path===''||path==='index.html')?'index.html':path;
 if(e.request.mode!=='navigate'&&!Object.hasOwn(HASHES,shellPath))return;
 e.respondWith((async()=>{
  const cache=await caches.open(CACHE);
  const response=await cache.match(fileURL(Object.hasOwn(HASHES,shellPath)?shellPath:'index.html'));
  // No network mixing of independently changing JS modules within a running release.
  return response||new Response('오프라인 파일을 찾지 못했습니다. 온라인에서 앱을 다시 열어 주세요.',{status:503,headers:{'Content-Type':'text/plain; charset=utf-8'}});
 })());
});
`;
const destination=resolve(root,'sw.js');
if(process.argv.includes('--check')){if(readFileSync(destination,'utf8')!==source){console.error('sw.js is stale. Run npm run prepare:release.');process.exit(1);}}else{writeFileSync(destination,source);console.log('Prepared verified offline release '+version);}
